# Template docker-compose.yml file - copy to docker-compose.yml and modify.
# Change the service names, container names, and exposed ports.
# Things to change: Everything in square brackets e.g. [mymysql], [8080]
version: '2'

services:
  [mymysql]:
    container_name: [mymysql]
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    ports:
      # Expose container MySQL port.
      - "[3307]:3306"
    volumes:
      - "../data/mysql:/var/lib/mysql"

  [mydrupal]:
    container_name: [mydrupal]
    # Eugene's custom PHP5 image for Drupal 7.
    image: eugenesia/drupal:php5-apache
    volumes:
      - "../data/drupal:/var/www/html"
      # Allow overriding php.ini with custom php.ini
      # - "./php.ini:/usr/local/etc/php/php.ini"
    # Expose container Apache port.
    ports:
      - "[8080]:80"
    depends_on:
      - [mymysql]

