# Template docker-compose.yml file - copy to docker-compose.yml and modify.
# Change the service names, container names, and exposed ports.
# Things to change: Everything in square brackets e.g. [mymysql], [8080]
version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    ports:
      # Expose container MySQL port.
      - "[3307]:3306"
    volumes:
      - "../data/mysql:/var/lib/mysql"
      # Configure MySQL for Drupal.
      - "./config/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf"


  # Web server config using PHPFarm and FastCGI for PHP 5.2 and
  # PHP 5.3.
  # See https://github.com/splitbrain/docker-phpfarm
  web:
    # Use splitbrain/phpfarm:wheezy if need to use PHP 5.2.
    image: splitbrain/phpfarm:jessie
    volumes:
      - "../data/drupal:/var/www"
      # Additional config for Apache Fcgid mod.
      - "./config/phpfarm.conf:/etc/apache2/conf.d/phpfarm.conf"
      # Allow overriding php.ini with custom php.ini
      # - "./config/php.ini:/var/www/.php/php.ini"
    # Expose container Apache port according to PHP version to use.
    # 8052: PHP 5.2, 8053: PHP 5.3, 8054: PHP 5.4, 8070: PHP 7.0, etc.
    # See https://github.com/splitbrain/docker-phpfarm
    ports:
      - "[8156]:8056"
    depends_on:
      - mysql


#   # Alternative setup using Apache and mod_php
#   web:
#     # Eugene's custom PHP5 image for Drupal 7.
#     # image: eugenesia/drupal-php:5.6-apache
#     volumes:
#       - "../data/drupal:/var/www/html"
#       # Allow overriding php.ini with custom php.ini
#       # - "./config/php.ini:/usr/local/etc/php/php.ini"
#     # Expose container Apache port according to PHP version to use.
#     # 8052: PHP 5.2, 8053: PHP 5.3, 8054: PHP 5.4, 8070: PHP 7.0, etc.
#     # See https://github.com/splitbrain/docker-phpfarm
#     ports:
#       - "[8080]:80"
#     depends_on:
#       - mysql

